### ISSUE TITLE
Capture variables using some sort of argument captor

### ISSUE THREAD

**Issue by reda-alaoui** [ununbium/HateoasUtils#6]
Today, when we need to resolve a variable value, we do something like:
```java
String id = ControllerUriResolver
.on(
  methodOn(FooController.class).findById(null)
)
.resolve("https://foo.com/1234", "id");
```
Being forced to use a string to identify the variable to resolve is sad. Especially when the system is almost totally type safe.

Mockito has an `ArgumentCaptor` allowing it to capture arguments in method calls.

I think it would be great to have a captor allowing to resolve method arguments like this:
```java
Captor idCaptor = Captor.build();

ControllerUriResolver
.on(
  methodOn(FooController.class).findById(idCaptor.capture())
)
.resolve("https://foo.com/1234");

String id = idCaptor;
```

**Comment by ununbium** [comment]
Hi Réda,

Thanks for your suggestion, I agree that the approach you've suggested would increase the type safety of the variable extraction code. However I think that there are a number of other factors to take into consideration while assessing how we want the API to work;


Firstly, due to the nature of how Spring rest declares rest end points (as annotations), the signature is not the strongest indicator of the behavior of the method or the meaning of the parameters. For the most part the extracted variables would be strings or basic types, in most common usage. This weakens the assertions based on signature alone. For example;

Code 1:
```java
@PostMapping("/owners/{pet_owner}/pet/{pet_name}")
public void saveResource(@RequestBody PetResource resource, @RequestParam(value = "pet_name"), String pet_name, @RequestParam(value = "pet_owner") String pet_owner)
```

is functionally identical to the following, while not sharing a method signature;

Code 2:
```java
@PostMapping("/owners/{pet_owner}/pet/{pet_name}")
public void saveResource(@RequestParam(value = "pet_owner") String pet_owner, @RequestParam(value = "pet_name") String pet_name, @RequestBody PetResource resource)
```

however code 1 shares a signature with the following, while the meaning is changed.

Code 3:
```java
@PostMapping("/locations/{pet_location}/pet/{pet_name}")
public void saveResource(@RequestBody PetResource resource, @RequestParam(value = "pet_location") String pet_location, @RequestParam(value = "pet_name") String pet_name)
```

In this case a lot of information is present in the annotations' parameters. The suggested approach of using argument captors would not be able to address this problem, in fact I'd argue that it would make the testing of these methods a little less clear by discarding important information. In other words, the parameter position is less meaningful than the name of the parameter that it is linked to.



The second concern is that the endpoint can have parameters that are not RequestParam, including @PathVariable, @RequestBody and @RequestHeader. There is no benefit I can think of in these elements being proxied (in the context of URL parameter extraction), which would mean that we would return to nulling those parameters or some proxy captor equivalent. For more complex end points at best this would not offer much of an improvement in the semantics, and a purist approach (requiring non-null proxies for each parameter) may actually need more boiler plate code.

Finally, the implementation of the described captor is somewhat tricky due to all of the previously mentioned (and other internal) interactions with Spring - it's not impossible but it would be a non trivial amount of development.

I'd recommend a test driven approach to asserting that the correct parameters are retrievable for a given URL and Controller reference combination using the existing mechanism. I agree it's not perfect but this is a result of the annotated nature of declaring Rest end points - an approach that has many upsides but occasionally backs us into a bit of a corner on verifiability and type safety. This trade-off is something that can also be seen with other Spring annotations like @Value and @Qualifier - not perfect, but certainly worth the code costs for the increased convenience and clarity that the features bring.

Thanks,
Andy
